# -*- coding: utf-8 -*-
"""Password_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/redr0y/learning-python-3980343/blob/main/Password_Generator.ipynb
"""

import random
import os
import requests

# Load a list of 10,000 common English words
word_file = "common_words.txt"
if not os.path.exists(word_file):
    url = "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt"
    response = requests.get(url)
    with open(word_file, "w") as f:
        f.write(response.text)

with open(word_file, "r") as f:
    # Using a range of 2 to 8 letters to ensure words fit perfectly
    all_words = [line.strip().lower() for line in f if 2 <= len(line.strip()) <= 8]

special_chars = ["!", "@", "#", "$", "*"]

print("Welcome to the Password Generator!\nBy: Isaac Blough")
print("\n>----------------< \n Lets get started \n>----------------<")

# Get user requirements
length = int(input("Total characters?: "))
num_count = int(input("How many numbers?: "))
spec_count = int(input("How many special characters?: "))

# Build the word part (Using combinations of whole words)
word_target = length - num_count - spec_count
chosen_string = ""

while len(chosen_string) < word_target:
    remaining_space = word_target - len(chosen_string)

    # Try to find a word that fits the remaining space exactly
    perfect_matches = [w for w in all_words if len(w) == remaining_space]

    if perfect_matches:
        chosen_string += random.choice(perfect_matches)
    else:
        # Otherwise, pick a word shorter than the space to leave room for one more word
        possible_options = [w for w in all_words if len(w) <= remaining_space - 2]
        if possible_options:
            chosen_string += random.choice(possible_options)
        else:
            # If we get stuck, restart the selection
            chosen_string = ""

# Capitalize first letter
final_word_part = chosen_string.capitalize()

# Generate numbers and special characters
num_part = "".join(str(random.randint(0, 9)) for _ in range(num_count))
spec_part = "".join(random.choice(special_chars) for _ in range(spec_count))

# Combine and Print
password = final_word_part + spec_part + num_part
print(f"\nYour generated password is: {password}")